const { app, BrowserWindow } = require('electron')
const path = require('path')
const { fork } = require('child_process')

let mainWindow
let serverProcess

function startNextJsServer() {
  const isDev = !app.isPackaged;
  // If packaged, run the standalone server generated by Next.js
  const serverPath = isDev
    ? path.join(__dirname, 'node_modules', '.bin', 'next')
    : path.join(__dirname, '.next', 'standalone', 'server.js')

  if (!isDev) {
    // In production (packaged), node is included or we assume it exists? No, electron runs Node.
    // However, fork requires a JS file. .next/standalone/server.js is perfect.
    serverProcess = fork(serverPath, [], {
      env: { ...process.env, PORT: '3000', NODE_ENV: 'production' }
    });
  } else {
    // We rely on concurrently starting next dev in dev mode
  }
}

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1280,
    height: 800,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // Wait a bit for the standalone server to start in prod
  if (app.isPackaged) {
    setTimeout(() => {
      mainWindow.loadURL('http://localhost:3000')
    }, 2000)
  } else {
    mainWindow.loadURL('http://localhost:3000')
  }

  mainWindow.on('closed', function () {
    mainWindow = null
  })
}

app.on('ready', () => {
  if (app.isPackaged) {
    startNextJsServer();
  }
  createWindow();
})

app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('before-quit', () => {
  if (serverProcess) {
    serverProcess.kill();
  }
})

app.on('activate', function () {
  if (mainWindow === null) {
    createWindow()
  }
})
